sonar.projectKey=note-app
sonar.projectName=Note App
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src/test,backend/src/test

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/prisma/**,\
  **/generated/**,\
  backend/src/generated/**,\
  backend/src/server.ts,\
  **/*.d.ts,\
  frontend/src/main.tsx,\
  frontend/src/vite-env.d.ts,\
  frontend/src/test/**,\
  backend/src/test/**

sonar.test.exclusions=\
  **/node_modules/**,\
  **/dist/**

sonar.javascript.lcov.reportPaths=\
  frontend/coverage/lcov.info,\
  backend/coverage/lcov.info

sonar.typescript.tsconfigPaths=\
  frontend/tsconfig.app.json,\
  backend/tsconfig.json

sonar.host.url=http://localhost:9000
sonar.token=sqp_e2db0992c2aa489627954143faa25f0eed4d9810